config/routes.rb
Rails.application.routes.draw do
  resources :bunches
  resources :genders
  resources :students
  root 'halo#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bunch.rb
class Bunch < ApplicationRecord
	has_many :student
end

app/models/gender.rb
class Gender < ApplicationRecord
	has_many :student
end

app/models/student.rb
class Student < ApplicationRecord
	belongs_to :gender
	belongs_to :bunch
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bunches_controller.rb
class BunchesController < ApplicationController
  before_action :set_bunch, only: [:show, :edit, :update, :destroy]

  # GET /bunches
  # GET /bunches.json
  def index
    @bunches = Bunch.all
  end

  # GET /bunches/1
  # GET /bunches/1.json
  def show
  end

  # GET /bunches/new
  def new
    @bunch = Bunch.new
  end

  # GET /bunches/1/edit
  def edit
  end

  # POST /bunches
  # POST /bunches.json
  def create
    @bunch = Bunch.new(bunch_params)

    respond_to do |format|
      if @bunch.save
        format.html { redirect_to @bunch, notice: 'Bunch was successfully created.' }
        format.json { render :show, status: :created, location: @bunch }
      else
        format.html { render :new }
        format.json { render json: @bunch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bunches/1
  # PATCH/PUT /bunches/1.json
  def update
    respond_to do |format|
      if @bunch.update(bunch_params)
        format.html { redirect_to @bunch, notice: 'Bunch was successfully updated.' }
        format.json { render :show, status: :ok, location: @bunch }
      else
        format.html { render :edit }
        format.json { render json: @bunch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bunches/1
  # DELETE /bunches/1.json
  def destroy
    @bunch.destroy
    respond_to do |format|
      format.html { redirect_to bunches_url, notice: 'Bunch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bunch
      @bunch = Bunch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bunch_params
      params.require(:bunch).permit(:name)
    end
end

app/controllers/genders_controller.rb
class GendersController < ApplicationController
  before_action :set_gender, only: [:show, :edit, :update, :destroy]

  # GET /genders
  # GET /genders.json
  def index
    @genders = Gender.all
  end

  # GET /genders/1
  # GET /genders/1.json
  def show
  end

  # GET /genders/new
  def new
    @gender = Gender.new
  end

  # GET /genders/1/edit
  def edit
  end

  # POST /genders
  # POST /genders.json
  def create
    @gender = Gender.new(gender_params)

    respond_to do |format|
      if @gender.save
        format.html { redirect_to @gender, notice: 'Gender was successfully created.' }
        format.json { render :show, status: :created, location: @gender }
      else
        format.html { render :new }
        format.json { render json: @gender.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genders/1
  # PATCH/PUT /genders/1.json
  def update
    respond_to do |format|
      if @gender.update(gender_params)
        format.html { redirect_to @gender, notice: 'Gender was successfully updated.' }
        format.json { render :show, status: :ok, location: @gender }
      else
        format.html { render :edit }
        format.json { render json: @gender.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genders/1
  # DELETE /genders/1.json
  def destroy
    @gender.destroy
    respond_to do |format|
      format.html { redirect_to genders_url, notice: 'Gender was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gender
      @gender = Gender.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gender_params
      params.require(:gender).permit(:name)
    end
end

app/controllers/halo_controller.rb
class HaloController < ApplicationController
  def index
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:npm, :name, :placebirth, :datebrith)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bunches_helper.rb
module BunchesHelper
end

app/helpers/genders_helper.rb
module GendersHelper
end

app/helpers/halo_helper.rb
module HaloHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/bunches/_form.html.erb
<%= form_for(bunch) do |f| %>
  <% if bunch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bunch.errors.count, "error") %> prohibited this bunch from being saved:</h2>

      <ul>
      <% bunch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bunches/edit.html.erb
<h1>Editing Bunch</h1>

<%= render 'form', bunch: @bunch %>

<%= link_to 'Show', @bunch %> |
<%= link_to 'Back', bunches_path %>

app/views/bunches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bunches</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bunches.each do |bunch| %>
      <tr>
        <td><%= bunch.name %></td>
        <td><%= link_to 'Show', bunch %></td>
        <td><%= link_to 'Edit', edit_bunch_path(bunch) %></td>
        <td><%= link_to 'Destroy', bunch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bunch', new_bunch_path %>

app/views/bunches/new.html.erb
<h1>New Bunch</h1>

<%= render 'form', bunch: @bunch %>

<%= link_to 'Back', bunches_path %>

app/views/bunches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bunch.name %>
</p>

<%= link_to 'Edit', edit_bunch_path(@bunch) %> |
<%= link_to 'Back', bunches_path %>

app/views/genders/_form.html.erb
<%= form_for(gender) do |f| %>
  <% if gender.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gender.errors.count, "error") %> prohibited this gender from being saved:</h2>

      <ul>
      <% gender.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/genders/edit.html.erb
<h1>Editing Gender</h1>

<%= render 'form', gender: @gender %>

<%= link_to 'Show', @gender %> |
<%= link_to 'Back', genders_path %>

app/views/genders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Genders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @genders.each do |gender| %>
      <tr>
        <td><%= gender.name %></td>
        <td><%= link_to 'Show', gender %></td>
        <td><%= link_to 'Edit', edit_gender_path(gender) %></td>
        <td><%= link_to 'Destroy', gender, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gender', new_gender_path %>

app/views/genders/new.html.erb
<h1>New Gender</h1>

<%= render 'form', gender: @gender %>

<%= link_to 'Back', genders_path %>

app/views/genders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gender.name %>
</p>

<%= link_to 'Edit', edit_gender_path(@gender) %> |
<%= link_to 'Back', genders_path %>

app/views/halo/index.html.erb
<h3>Menu</h3>
<ul>
	<li><%= link_to "Student", students_path %></li>
	<li><%= link_to "Gender", genders_path %></li>
	<li><%= link_to "Bunch" , bunches_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_for(student) do |f| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :npm %>
    <%= f.number_field :npm %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :placebirth %>
    <%= f.text_field :placebirth %>
  </div>

  <div class="field">
    <%= f.label :datebrith %>
    <%= f.date_select :datebrith %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>Npm</th>
      <th>Name</th>
      <th>Placebirth</th>
      <th>Datebrith</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.npm %></td>
        <td><%= student.name %></td>
        <td><%= student.placebirth %></td>
        <td><%= student.datebrith %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Npm:</strong>
  <%= @student.npm %>
</p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Placebirth:</strong>
  <%= @student.placebirth %>
</p>

<p>
  <strong>Datebrith:</strong>
  <%= @student.datebrith %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>